### ISSUE TITLE
IDS_T1_MAPA MENTAL

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/actividad-1-mapa-mental-KarlaV0#1]
[IDS_T1_MAPA MENTAL.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-KarlaV0/files/10688291/IDS_T1_MAPA.MENTAL.pdf)

**Comment by Heidi-19** [comment]
Calificación: 18%

**Comment by Heidi-19** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
